### ISSUE TITLE
Create combined PCA plot

### ISSUE THREAD

**Issue by krademaker** [DaanJG98/RNA-seq-analysis#6]
Create combined PCA plot to show separation of replicates per strain/growth condition.

https://github.com/DaanJG98/RNA-seq-analysis/blob/5d117fc3eb666885b417582c328eb6739904dfc7/binf_cou11_rnaseq.r#L47

**Comment by krademaker** [comment]
http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/112-pca-principal-component-analysis-essentials/

**Comment by SBongers** [comment]
Job done
