### ISSUE TITLE
Create branch for updated annotation

### ISSUE THREAD

**Issue by krademaker** [DaanJG98/RNA-seq-analysis#8]
https://github.com/DaanJG98/RNA-seq-analysis/blob/b9e2494cb78c7af83da3a0f7cecf8fc282d0b4c6/binf_cou11_rnaseq.r#L128-L132

- Create new R-script to get updated annotation.
- Store updated annotation to new file (.txt)
- AnnotateDEGenes should remain the same, only the input Annotation has to be changed.

**Comment by DaanJG98** [comment]
https://www.rdocumentation.org/packages/rtracklayer/versions/1.32.1/topics/readGFF


Pseudo code:
```
source("https://bioconductor.org/biocLite.R")
biocLite("rtracklayer")
library("rtracklayer")
file <- import.gff3("file.gff", columns=c([relevante columns]))

for (row in file){
  if type equals GENE
  get ID
  next row:
    if type equals CDS:
       if parent equals previous_row.ID
          retrieve required data and save in dataframe
          next GENE
}
```
